# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('addressInfor', models.CharField(max_length=200)),
                ('isShow', models.BooleanField(default=1)),
                ('isDefault', models.BooleanField()),
                ('addPeople', models.CharField(max_length=20)),
                ('addPhone', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaId', models.AutoField(primary_key=True, serialize=False)),
                ('areaName', models.CharField(max_length=20)),
                ('isShow', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provinceId', models.AutoField(primary_key=True, serialize=False)),
                ('provinceName', models.CharField(max_length=20)),
                ('isShow', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=11)),
                ('userPwd', models.CharField(max_length=90)),
                ('registerTime', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('isShow', models.BooleanField(default=1)),
                ('loginTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('userPic', models.CharField(blank=True, max_length=200, null=True)),
                ('userEmail', models.CharField(max_length=50)),
                ('userPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('userSex', models.BooleanField(default=1)),
                ('areaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='provinceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='areaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Area'),
        ),
        migrations.AddField(
            model_name='address',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
