# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('colorId', models.AutoField(primary_key=True, serialize=False)),
                ('colorName', models.CharField(max_length=32)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isShow', models.BooleanField(choices=[(True, '\u662f'), (False, '\u5426')], default=True, verbose_name='\u662f\u5426\u542f\u7528')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('materialId', models.AutoField(primary_key=True, serialize=False)),
                ('materialName', models.CharField(max_length=20)),
                ('isShow', models.BooleanField(choices=[(True, '\u662f'), (False, '\u5426')], default=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProductClass',
            fields=[
                ('parentProductClassId', models.AutoField(primary_key=True, serialize=False)),
                ('parentName', models.CharField(max_length=20)),
                ('isShow', models.BooleanField(choices=[(True, '\u662f'), (False, '\u5426')], default=True, verbose_name='\u662f\u5426\u542f\u7528')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('productRemainder', models.IntegerField()),
                ('productIntroduction', models.TextField(blank=True, null=True)),
                ('isRecommendation', models.BooleanField(default=1)),
                ('isShow', models.BooleanField(choices=[(True, '\u662f'), (False, '\u5426')], default=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('picture', models.CharField(blank=True, default=0, max_length=300, null=True)),
                ('miniPicture', models.CharField(blank=True, default=0, max_length=300, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('productInfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('productClassId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=20)),
                ('isShow', models.BooleanField(choices=[(True, '\u662f'), (False, '\u5426')], default=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('parentProductClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ParentProductClass')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='isShow',
            field=models.BooleanField(choices=[(True, '\u662f'), (False, '\u5426')], default=True, verbose_name='\u662f\u5426\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='area',
            name='isShow',
            field=models.BooleanField(choices=[(True, '\u662f'), (False, '\u5426')], default=True, verbose_name='\u662f\u5426\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='province',
            name='isShow',
            field=models.BooleanField(choices=[(True, '\u662f'), (False, '\u5426')], default=True, verbose_name='\u662f\u5426\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isShow',
            field=models.BooleanField(choices=[(True, '\u662f'), (False, '\u5426')], default=True, verbose_name='\u662f\u5426\u542f\u7528'),
        ),
        migrations.AddField(
            model_name='product',
            name='productClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProductClass'),
        ),
    ]
