# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171228_2148'),
        ('admina', '0001_initial'),
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trolley',
            fields=[
                ('trolleyId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('colorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admina.ProductAndColor')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admina.Product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
